version: "3.9"
services:

  etcd-0:
    image: etcd-node:latest
    build: .
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./entrypoint.sh:/var/lib/etcd-data/entrypoint.sh
    env_file:
      - .env
    deploy:
      replicas: 3

networks:
  default:
    external:
      name: etcd-cluster-network

